services:
  # --- Backend Service ---
  - type: web
    name: zerodha-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 3002
      - key: NODE_ENV
        value: production

  # --- Frontend Service ---
  - type: web
    name: zerodha-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://zerodha-backend.onrender.com

  # --- Dashboard (Optional) ---
  # Remove this block if your dashboard is part of frontend
  - type: web
    name: zerodha-dashboard
    env: static
    plan: free
    rootDir: dashboard
    buildCommand: "npm install && npm run build"
    staticPublishPath: build